# Generated by Django 5.1.7 on 2025-04-18 03:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('document_block', 0), ('image_block', 1), ('video_block', 9), ('markdown_block', 10)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full', 'label': '文档块'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': '图片块'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('upload', '上传视频'), ('youtube', 'YouTube链接'), ('bilibili', 'Bilibili链接'), ('vimeo', 'Vimeo链接')], 'icon': 'media', 'label': '视频类型'}), 3: ('wagtail.blocks.CharBlock', (), {'label': '上传视频路径', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': '外部视频链接', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': '自动播放', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': '循环播放', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': '静音', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '视频封面', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('video_type', 2), ('uploaded_video_path', 3), ('external_video_url', 4), ('autoplay', 5), ('loop', 6), ('muted', 7), ('thumbnail', 8)]], {'icon': 'media', 'label': '视频块'}), 10: ('blog.models.MarkdownBlock', (), {'icon': 'code', 'label': 'Markdown块'})}, default=[], null=True, verbose_name='内容'),
        ),
    ]
