"""增加news模块

Revision ID: 15c18b4fc8a1
Revises: 8c07f0c12665
Create Date: 2024-11-07 22:04:09.569568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c18b4fc8a1'
down_revision = '8c07f0c12665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_type',
    sa.Column('type_name', sa.String(length=50), nullable=False, comment='新闻类型名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级id'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('title', sa.String(length=100), nullable=False, comment='新闻标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='新闻内容'),
    sa.Column('news_type_id', sa.Integer(), nullable=False, comment='新闻类型id'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['news_type_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('news_type')
    # ### end Alembic commands ###
