"""修改comment类

Revision ID: 2374e3d1675e
Revises: 83c4e8549e81
Create Date: 2024-10-23 19:18:01.347040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2374e3d1675e'
down_revision = '83c4e8549e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='分类名称',
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment='父分类',
               existing_nullable=True)

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父分类',
               existing_nullable=True)
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
