"""修改sex

Revision ID: 24b862ca88fc
Revises: 5a83bac9645c
Create Date: 2024-10-08 16:41:44.912046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b862ca88fc'
down_revision = '5a83bac9645c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
