"""Initial migration

Revision ID: 3c7ec83573c1
Revises: 
Create Date: 2024-11-16 14:53:46.926629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7ec83573c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('type_name', sa.String(length=20), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类'),
    sa.ForeignKeyConstraint(['parent_id'], ['article_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品id'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='商品名称'),
    sa.Column('price', sa.Float(), nullable=False, comment='商品价格'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品描述'),
    sa.Column('image', sa.String(length=128), nullable=True, comment='商品图片'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_type',
    sa.Column('type_name', sa.String(length=50), nullable=False, comment='新闻类型名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级id'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('register_time', sa.DATETIME(), nullable=False, comment='注册时间'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='标题'),
    sa.Column('description', sa.String(length=128), nullable=True, comment='文章描述'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('publish_time', sa.DATETIME(), nullable=False, comment='发布时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('read_count', sa.Integer(), nullable=False, comment='阅读次数'),
    sa.Column('collect_count', sa.Integer(), nullable=False, comment='收藏次数'),
    sa.Column('comment_count', sa.Integer(), nullable=False, comment='评论次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞次数'),
    sa.Column('comment_status', sa.Boolean(), nullable=False, comment='评论状态'),
    sa.Column('background_image', sa.String(length=128), nullable=True, comment='背景图片路径'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('type_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.ForeignKeyConstraint(['type_id'], ['article_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('title', sa.String(length=100), nullable=False, comment='新闻标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='新闻内容'),
    sa.Column('news_type_id', sa.Integer(), nullable=False, comment='新闻类型id'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['news_type_id'], ['news_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_album',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='相册名称'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='相册路径'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='相册描述'),
    sa.Column('album_datetime', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goods_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('realname', sa.String(length=64), nullable=False, comment='真实姓名'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('sex', sa.SmallInteger(), nullable=False, comment='性别'),
    sa.Column('content', sa.String(length=255), nullable=False, comment='关于我内容'),
    sa.Column('publish_time', sa.DATETIME(), nullable=False, comment='发布时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('article_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('file_name', sa.String(length=128), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=128), nullable=False, comment='文件路径'),
    sa.Column('file_type', sa.String(length=64), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('upload_time', sa.DATETIME(), nullable=False, comment='上传时间'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('content_type', sa.String(length=64), nullable=False, comment='附件类型'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('comment_time', sa.DATETIME(), nullable=False, comment='评论时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article_file')
    op.drop_table('userinfo')
    op.drop_table('user_goods_association')
    op.drop_table('user_album')
    op.drop_table('news')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('news_type')
    op.drop_table('goods')
    op.drop_table('article_type')
    # ### end Alembic commands ###
