"""增加user.content

Revision ID: 4189dc6f90ba
Revises: 2374e3d1675e
Create Date: 2024-10-25 11:04:42.374708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4189dc6f90ba'
down_revision = '2374e3d1675e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=255), nullable=False, comment='关于我内容'))
        batch_op.add_column(sa.Column('publish_time', sa.DATETIME(), nullable=False, comment='发布时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('publish_time')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
