"""修改sex

Revision ID: 5a83bac9645c
Revises: d60ad27db5b8
Create Date: 2024-10-08 16:38:46.946908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a83bac9645c'
down_revision = 'd60ad27db5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.SmallInteger(), nullable=False))
        batch_op.drop_column('Sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sex', mysql.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
