"""user.email修改为唯一值

Revision ID: 621b20549597
Revises: 4189dc6f90ba
Create Date: 2024-11-02 22:30:51.785607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621b20549597'
down_revision = '4189dc6f90ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
