"""修改goods类，增加image图片，以及逻辑删除

Revision ID: 74557cd045a5
Revises: 621b20549597
Create Date: 2024-11-07 09:54:45.039205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74557cd045a5'
down_revision = '621b20549597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True, comment='商品图片'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='商品id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='商品名称',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment='商品价格',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='商品描述',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='商品描述',
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='商品价格',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='商品id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
