"""增加注释

Revision ID: 8387ed3ef546
Revises: 16cd2d110749
Create Date: 2024-10-23 11:23:06.103713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8387ed3ef546'
down_revision = '16cd2d110749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128),
               comment='标题',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='文章描述',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               comment='文章内容',
               existing_nullable=False)
        batch_op.alter_column('publish_time',
               existing_type=mysql.DATETIME(),
               comment='发布时间',
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=False)
        batch_op.alter_column('read_count',
               existing_type=mysql.INTEGER(),
               comment='阅读次数',
               existing_nullable=False)
        batch_op.alter_column('collect_count',
               existing_type=mysql.INTEGER(),
               comment='收藏次数',
               existing_nullable=False)
        batch_op.alter_column('comment_count',
               existing_type=mysql.INTEGER(),
               comment='评论次数',
               existing_nullable=False)
        batch_op.alter_column('like_count',
               existing_type=mysql.INTEGER(),
               comment='点赞次数',
               existing_nullable=False)
        batch_op.alter_column('comment_status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='评论状态',
               existing_nullable=False)
        batch_op.alter_column('background_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='背景图片路径',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('article_file', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='文件名',
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='文件路径',
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment='文件类型',
               existing_nullable=True)
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(),
               comment='文件大小',
               existing_nullable=True)
        batch_op.alter_column('upload_time',
               existing_type=mysql.DATETIME(),
               comment='上传时间',
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=mysql.INTEGER(),
               comment='文章ID',
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='评论内容',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=mysql.INTEGER(),
               comment='文章ID',
               existing_nullable=False)
        batch_op.alter_column('comment_time',
               existing_type=mysql.DATETIME(),
               comment='评论时间',
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment='父评论ID',
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='密码',
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment='手机号',
               existing_nullable=False)
        batch_op.alter_column('register_time',
               existing_type=mysql.DATETIME(),
               comment='注册时间',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='头像',
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=False)

    with op.batch_alter_table('user_album', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='相册名称',
               existing_nullable=False)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='相册路径',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='相册描述',
               existing_nullable=True)
        batch_op.alter_column('album_datetime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('realname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment='真实姓名',
               existing_nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               comment='年龄',
               existing_nullable=False)
        batch_op.alter_column('sex',
               existing_type=mysql.SMALLINT(),
               comment='性别',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=mysql.SMALLINT(),
               comment=None,
               existing_comment='性别',
               existing_nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='年龄',
               existing_nullable=False)
        batch_op.alter_column('realname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment=None,
               existing_comment='真实姓名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_album', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('album_datetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='相册描述',
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='相册路径',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='相册名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
        batch_op.alter_column('register_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='注册时间',
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment=None,
               existing_comment='手机号',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父评论ID',
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False)
        batch_op.alter_column('comment_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='评论时间',
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文章ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='评论内容',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('article_file', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文章ID',
               existing_nullable=False)
        batch_op.alter_column('upload_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='上传时间',
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文件大小',
               existing_nullable=True)
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment=None,
               existing_comment='文件类型',
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='文件路径',
               existing_nullable=False)
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='文件名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('background_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='背景图片路径',
               existing_nullable=True)
        batch_op.alter_column('comment_status',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='评论状态',
               existing_nullable=False)
        batch_op.alter_column('like_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点赞次数',
               existing_nullable=False)
        batch_op.alter_column('comment_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='评论次数',
               existing_nullable=False)
        batch_op.alter_column('collect_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='收藏次数',
               existing_nullable=False)
        batch_op.alter_column('read_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='阅读次数',
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False)
        batch_op.alter_column('publish_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='发布时间',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='文章内容',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='文章描述',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
