"""修改注释

Revision ID: 83c4e8549e81
Revises: 8387ed3ef546
Create Date: 2024-10-23 11:26:10.463851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83c4e8549e81'
down_revision = '8387ed3ef546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               comment='分类ID',
               existing_nullable=True)

    with op.batch_alter_table('article_file', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment='附件类型',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_file', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment=None,
               existing_comment='附件类型',
               existing_nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分类ID',
               existing_nullable=True)

    # ### end Alembic commands ###
