"""修改时间属性

Revision ID: 8c07f0c12665
Revises: 74557cd045a5
Create Date: 2024-11-07 15:03:08.541748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c07f0c12665'
down_revision = '74557cd045a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.drop_column('update_time')

    # ### end Alembic commands ###
