"""修改article字段

Revision ID: 9298a8036002
Revises: 5b710a4cdf64
Create Date: 2024-10-12 08:56:40.471396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9298a8036002'
down_revision = '5b710a4cdf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               nullable=True)

    # ### end Alembic commands ###
