"""修改文章背景图片名称，增加图片相关文件类，以及用户相册类

Revision ID: d54ff4cbc358
Revises: 28ba42b9163c
Create Date: 2024-10-18 17:36:26.687639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd54ff4cbc358'
down_revision = '28ba42b9163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_album',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('album_datetime', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=128), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DATETIME(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('background_image')

    op.drop_table('article_file')
    op.drop_table('user_album')
    # ### end Alembic commands ###
