"""增加grade

Revision ID: 144a24323645
Revises: e7ea3e29176e
Create Date: 2024-10-21 10:25:31.929695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144a24323645'
down_revision = 'e7ea3e29176e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_grade',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生id'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程id'),
    sa.Column('grade', sa.Numeric(precision=5, scale=2), nullable=False, comment='成绩'),
    sa.Column('time', sa.DateTime(), nullable=False, comment='考试时间'),
    sa.ForeignKeyConstraint(['course_id'], ['db_course_1.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['db_students_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_grade')
    # ### end Alembic commands ###
