"""增加stuent、studentinfo、tearcher、course

Revision ID: 2c2eadeb5952
Revises: 
Create Date: 2024-10-20 20:03:34.821950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2eadeb5952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_course_1',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='课程'),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False, comment='价格'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('db_students_1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=15), nullable=False, comment='姓名'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='年龄'),
    sa.Column('sex', sa.Boolean(), nullable=False, comment='性别'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱地址'),
    sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=False, comment='钱包'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('db_teacher',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('option', sa.Enum('讲师', '助教', '班主任'), nullable=False, comment='职位'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('register_time', sa.DATETIME(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('db_student_info_1',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('qq_num', sa.String(length=15), nullable=True, comment='QQ号'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='学生id'),
    sa.ForeignKeyConstraint(['user_id'], ['db_students_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('realname', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('Sex', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.drop_table('db_student_info_1')
    op.drop_table('user')
    op.drop_table('db_teacher')
    op.drop_table('db_students_1')
    op.drop_table('db_course_1')
    # ### end Alembic commands ###
