"""增加studentadress

Revision ID: e7ea3e29176e
Revises: 2c2eadeb5952
Create Date: 2024-10-21 09:26:46.819815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7ea3e29176e'
down_revision = '2c2eadeb5952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_student_address_1',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='学生id'),
    sa.Column('province', sa.String(length=20), nullable=False, comment='省份'),
    sa.Column('city', sa.String(length=20), nullable=False, comment='城市'),
    sa.Column('area', sa.String(length=20), nullable=False, comment='区县'),
    sa.Column('address', sa.String(length=200), nullable=False, comment='详细地址'),
    sa.ForeignKeyConstraint(['user_id'], ['db_students_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('db_student_info_1', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='默认地址',
               existing_comment='地址',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_student_info_1', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='地址',
               existing_comment='默认地址',
               existing_nullable=True)

    op.drop_table('db_student_address_1')
    # ### end Alembic commands ###
