# 邮件验证链接有效期：一天
VERIFY_EMAIL_TOKEN_EXPIRES = 60 * 60 * 24

# 用户地址上限
USER_ADDRESS_COUNTS_LIMIT = 20

# 用户浏览历史记录上限
USER_BROWSING_HISTORY_COUNTS_LIMIT = 5

# 用户浏览历史记录时间上线
USER_BROWSING_HISTORY_EXPIRES = 60 * 60 * 24 * 30