# Generated by Django 4.1.13 on 2024-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_bookinfo_options_alter_peopleinfo_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="名字"),
        ),
        migrations.AlterField(
            model_name="peopleinfo",
            name="name",
            field=models.CharField(max_length=50, verbose_name="名称"),
        ),
    ]
