"""AUTOMATIC模型

Revision ID: 1e248a7b76a8
Revises: 
Create Date: 2024-11-14 10:49:22.294537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e248a7b76a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automatic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automatic')
    # ### end Alembic commands ###
