"""AUTOMATIC模型

Revision ID: ac300d26f781
Revises: 1e248a7b76a8
Create Date: 2024-11-14 10:50:59.058463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac300d26f781'
down_revision = '1e248a7b76a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automatic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=255), nullable=False, comment='密码'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automatic', schema=None) as batch_op:
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
