# Generated by Django 5.2.7 on 2025-11-13 12:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_merge_20250811_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('mermaid_chart', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': '大标题'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': '段落内容'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '在此处粘贴您的 Mermaid.js 语法代码 (例如: graph TD; A-->B;)', 'label': 'Mermaid 代码'}), 3: ('wagtail.blocks.StructBlock', [[('code', 2)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
