# Generated by Django 5.1.7 on 2025-04-29 13:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_remove_searchpromotion_query_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='页面介绍')),
            ],
            options={
                'verbose_name': '博客索引页',
                'verbose_name_plural': '博客索引页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='发布日期')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('intro', models.TextField(max_length=250, verbose_name='简介')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1), ('table', 2), ('media', 3), ('audio', 4), ('video', 5), ('embed', 6), ('raw_html', 7)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'label': '富文本'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code', 'label': 'Markdown'}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 3: ('blog.models.CustomMediaBlock', (), {'icon': 'media', 'label': '媒体'}), 4: ('wagtailmedia.blocks.AudioChooserBlock', (), {'icon': 'media', 'label': '音频'}), 5: ('wagtailmedia.blocks.VideoChooserBlock', (), {'icon': 'media', 'label': '视频'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': '从YouTube、Vimeo等插入内容', 'label': '嵌入媒体'}), 7: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '适用于高级用户的HTML代码插入', 'label': '原始HTML'})}, verbose_name='内容主体')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='特色图片')),
            ],
            options={
                'verbose_name': '技术博客',
                'verbose_name_plural': '技术博客',
            },
            bases=('wagtailcore.page',),
        ),
    ]
